// Football Factory — initial competition registry.
// Phase 1.A scope: 14 competitions covering PL/LaLiga/Bundesliga/Serie A/
// Ligue 1 + UCL/UEL/UECL + 6 domestic cups. provider_ids are populated for
// football-data.org (string code) and API-Football (numeric league id);
// some IDs are placeholders that Phase 1.B will validate against live APIs.

import type { CompetitionRegistryEntry } from './types';

export const COMPETITION_REGISTRY: readonly CompetitionRegistryEntry[] = [
  // ----- Domestic leagues -----
  {
    canonical_id: 'league:premier-league',
    name: 'Premier League',
    short_name: 'PL',
    country: 'England',
    competition_type: 'league',
    priority: 100,
    enabled: true,
    aliases: ['EPL', 'พรีเมียร์ลีก'],
    provider_ids: { 'football-data.org': 'PL', 'api-football': 39 },
  },
  {
    canonical_id: 'league:laliga',
    name: 'LaLiga',
    short_name: 'PD',
    country: 'Spain',
    competition_type: 'league',
    priority: 95,
    enabled: true,
    aliases: ['La Liga', 'ลาลีกา'],
    provider_ids: { 'football-data.org': 'PD', 'api-football': 140 },
  },
  {
    canonical_id: 'league:bundesliga',
    name: 'Bundesliga',
    short_name: 'BL1',
    country: 'Germany',
    competition_type: 'league',
    priority: 95,
    enabled: true,
    aliases: ['บุนเดสลีกา'],
    provider_ids: { 'football-data.org': 'BL1', 'api-football': 78 },
  },
  {
    canonical_id: 'league:serie-a',
    name: 'Serie A',
    short_name: 'SA',
    country: 'Italy',
    competition_type: 'league',
    priority: 90,
    enabled: true,
    aliases: ['เซเรีย อา'],
    provider_ids: { 'football-data.org': 'SA', 'api-football': 135 },
  },
  {
    canonical_id: 'league:ligue-1',
    name: 'Ligue 1',
    short_name: 'FL1',
    country: 'France',
    competition_type: 'league',
    priority: 85,
    enabled: true,
    aliases: ['ลีกเอิง'],
    provider_ids: { 'football-data.org': 'FL1', 'api-football': 61 },
  },

  // ----- European competitions -----
  {
    canonical_id: 'competition:uefa-champions-league',
    name: 'UEFA Champions League',
    short_name: 'UCL',
    country: 'UEFA',
    competition_type: 'continental',
    priority: 100,
    enabled: true,
    aliases: ['Champions League', 'UEFA Champions League', 'UEFA-Champions-League', 'ยูฟ่า แชมเปียนส์ลีก'],
    provider_ids: { 'football-data.org': 'CL', 'api-football': 2 },
  },
  {
    canonical_id: 'competition:uefa-europa-league',
    name: 'UEFA Europa League',
    short_name: 'UEL',
    country: 'UEFA',
    competition_type: 'continental',
    priority: 80,
    enabled: true,
    aliases: ['Europa League'],
    provider_ids: { 'football-data.org': 'EL', 'api-football': 3 },
  },
  {
    canonical_id: 'competition:uefa-conference-league',
    name: 'UEFA Conference League',
    short_name: 'UECL',
    country: 'UEFA',
    competition_type: 'continental',
    priority: 75,
    enabled: true,
    aliases: ['Conference League'],
    provider_ids: { 'football-data.org': 'ECL', 'api-football': 848 },
  },

  // ----- Domestic cups -----
  {
    canonical_id: 'cup:fa-cup',
    name: 'FA Cup',
    short_name: 'FAC',
    country: 'England',
    competition_type: 'cup',
    priority: 60,
    enabled: true,
    aliases: ['The FA Cup'],
    provider_ids: { 'football-data.org': 'FAC', 'api-football': 45 },
  },
  {
    canonical_id: 'cup:carabao-cup',
    name: 'Carabao Cup',
    short_name: 'LC',
    country: 'England',
    competition_type: 'cup',
    priority: 50,
    enabled: true,
    aliases: ['EFL Cup', 'League Cup'],
    provider_ids: { 'football-data.org': 'LC', 'api-football': 48 },
  },
  {
    canonical_id: 'cup:copa-del-rey',
    name: 'Copa del Rey',
    short_name: 'CDR',
    country: 'Spain',
    competition_type: 'cup',
    priority: 60,
    enabled: true,
    aliases: ['คัลปา เดล เรย์'],
    provider_ids: { 'football-data.org': 'CDR', 'api-football': 143 },
  },
  {
    canonical_id: 'cup:dfb-pokal',
    name: 'DFB-Pokal',
    short_name: 'DFB',
    country: 'Germany',
    competition_type: 'cup',
    priority: 60,
    enabled: true,
    aliases: ['German Cup'],
    provider_ids: { 'football-data.org': 'DFB', 'api-football': 81 },
  },
  {
    canonical_id: 'cup:coppa-italia',
    name: 'Coppa Italia',
    short_name: 'CIT',
    country: 'Italy',
    competition_type: 'cup',
    priority: 60,
    enabled: true,
    aliases: ['Italian Cup'],
    provider_ids: { 'football-data.org': 'CIT', 'api-football': 137 },
  },
  {
    canonical_id: 'cup:coupe-de-france',
    name: 'Coupe de France',
    short_name: 'CDF',
    country: 'France',
    competition_type: 'cup',
    priority: 55,
    enabled: true,
    aliases: ['French Cup'],
    provider_ids: { 'football-data.org': 'CDF', 'api-football': 66 },
  },
] as const;
